In [ ]:
#Exploratory Data Analysis Project
#Using Netflix Dataset

In [7]:
import pandas as pd
import matplotlib as plt
import seaborn as sns
import numpy as np

In [12]:
df = pd.read_csv('/Users/vipulbhatti/Desktop/Programming Projects/Python/Data Analysis/Exploratory-Data-Analysis/ml-latest-small/movies.csv')
print(df)

      movieId                                      title  \
0           1                           Toy Story (1995)
1           2                             Jumanji (1995)
2           3                    Grumpier Old Men (1995)
3           4                   Waiting to Exhale (1995)
4           5         Father of the Bride Part II (1995)
...       ...                                        ...
9737   193581  Black Butler: Book of the Atlantic (2017)
9738   193583               No Game No Life: Zero (2017)
9739   193585                               Flint (2017)
9740   193587        Bungo Stray Dogs: Dead Apple (2018)
9741   193609        Andrew Dice Clay: Dice Rules (1991)

                                           genres
0     Adventure|Animation|Children|Comedy|Fantasy
1                      Adventure|Children|Fantasy
2                                  Comedy|Romance
3                            Comedy|Drama|Romance
4                                          Comedy
...                                           ...
9737              Action|Animation|Comedy|Fantasy
9738                     Animation|Comedy|Fantasy
9739                                        Drama
9740                             Action|Animation
9741                                       Comedy

[9742 rows x 3 columns]

In [10]:
#First five rows of dataset
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [11]:
#Last five rows of dataset
df.tail()

,movieId,title,genres
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [14]:
#Checked how many rows and columns there are in the dataset
df.shape

(9742, 3)

In [17]:
#Shows stats for different types of columns (numerical, non-numerical etc)
df.describe(include='all')

              movieId        title genres
count     9742.000000         9742   9742
unique            NaN         9737    951
top               NaN  Emma (1996)  Drama
freq              NaN            2   1053
mean     42200.353623          NaN    NaN
std      52160.494854          NaN    NaN
min          1.000000          NaN    NaN
25%       3248.250000          NaN    NaN
50%       7300.000000          NaN    NaN
75%      76232.000000          NaN    NaN
max     193609.000000          NaN    NaN

In [18]:
#Check how many null/missing values there are
df.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [28]:
#Renamed columns for more professional and grammatically correct names

df.rename(columns={
    'movieID' : 'Movie ID',
    'title' : 'Title',
    'genres' : 'Genres'
}, inplace=True)

df.columns

Index(['movieId', 'Title', 'Genres'], dtype='object')

In [30]:
#Split genres string into lists using "|" separator
df['Genres_list'] = df['Genres'].apply(lambda x : x.split('|'))

df['Genres_list']

0       [Adventure, Animation, Children, Comedy, Fantasy]
1                          [Adventure, Children, Fantasy]
2                                       [Comedy, Romance]
3                                [Comedy, Drama, Romance]
4                                                [Comedy]
                              ...
9737                 [Action, Animation, Comedy, Fantasy]
9738                         [Animation, Comedy, Fantasy]
9739                                              [Drama]
9740                                  [Action, Animation]
9741                                             [Comedy]
Name: Genres_list, Length: 9742, dtype: object

In [32]:
#Basic Genre Frequency Analysis 


genre_counts = df.explode('Genre_list')['Genre_list'].value_counts()
print(genre_counts)

KeyError: 'Typ'